# This is a basic workflow to help you get started with Actions
name: Deploy to S3 bucket

on:
  push:
    branches:
    - main

jobs:
  deploy_s3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      # - name: Configure AWS credentials
      #   id: aws-configure-credentials
      #   uses: aws-actions/configure-aws-credentials@ea7b857d8a33dc2fb4ef5a724500044281b49a5e
      #   with:
      #     aws-access-key-id: ${{ secrets.ACCESS_KEY }}
      #     aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
      #     role-duration-seconds: 3600
      #     aws-region: us-west-2
        
      - name: npm install & build
        run: |
          npm install
          npm run build


      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

      # - name: Deploy and S3 sync
      #   uses: reggionick/s3-deploy@v3
      #   #uses: jakejarvis/s3-sync-action@main
      #   with:
      #     folder: .next
      #     bucket: ${{ secrets.AWS_S3_BUCKET }}
      #     bucket-region: us-west-2
      #     #dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #     invalidation: /
      #     delete-removed: true
      #     no-cache: true
      #     private: true
      
